<?php

/**
 * ldap_listing.install
 *
 * ldap_listing
 */

/**
 * Update configuration schema for 1.2
 */
function ldap_listing_update_9101() {
  // Add 'depth' property to each directory section config.
  $configFactory = \Drupal::configFactory();
  foreach ($configFactory->listAll('ldap_listing.directory_section.') as $name) {
    $config = $configFactory->getEditable($name);
    $config->set('depth',1);
    $config->save();
  }
}

/**
 * Local Variables:
 * mode:php
 * End:
 */
