<?php

/**
 * ldap_listing.module
 *
 * ldap_listing
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\ldap_listing\Controller\DirectoryPage;

/**
 * Implements hook_help().
 */
function ldap_listing_help($route_name,RouteMatchInterface $route_match) {
  switch ($route_name) {
  case 'help.page.ldap_listing':
    return '
      <h2>LDAP Directory</h2>
      <p>This module generates a directory listing page for entities queried from an LDAP server.</p>
      ';
  }
}

/**
 * Implements hook_theme().
 */
function ldap_listing_theme($existing,$type,$theme,$path) {
  return [
    'ldap_listing_directory_listing' => [
      'variables' => [
        'index' => null,
      ],
    ],
  ];
}

/**
 * Implements hook_cron().
 */
function ldap_listing_cron() {
  DirectoryPage::invalidateIfElapsed();
}

/**
 * Local Variables:
 * mode:php
 * End:
 */
