ldap_listing.directory_section.*:
  type: config_entity
  label: 'Directory Listing Section config'
  mapping:
    id:
      type: string
      label: 'Machine name for this directory listing section configuration'
    uuid:
      type: string
    label:
      type: string
      name: 'Display name for section'
    abbrev:
      type: string
      name: 'Abbreviation'
    group_dn:
      type: string
      name: 'DN of LDAP group'
    weight:
      type: integer
      name: 'Weight'
