<?php

/**
 * DirectoryQuery.php
 *
 * ldap_listing
 */

namespace Drupal\ldap_listing;

use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\ldap_listing\Form\SettingsForm;
use Drupal\ldap_servers\LdapBridgeInterface;

class DirectoryQuery {
  private $config;

  /**
   * @var \Drupal\ldap_servers\LdapBridgeInterface
   */
  private $ldapBridge;

  /**
   * @var \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  private $entityTypeManager;

  /**
   * @var \Drupal\Core\Entity\EntityStorageInterface
   */
  private $storage;

  /**
   * @var \Drupal\ldap_servers\ServerInterface
   */
  private $ldapServer;

  /**
   * Creates a new DirectoryQuery instance.
   *
   * @param \Drupal\Core\Entity\EntityTypeManagerInterface
   */
  public function __construct(
    EntityTypeManagerInterface $entityTypeManager,
    LdapBridgeInterface $ldapBridge)
  {
    $this->ldapBridge = $ldapBridge;
    $this->entityTypeManager = $entityTypeManager;
    $this->storage = $entityTypeManager->getStorage('ldap_listing_directory_section');

    $this->config = \Drupal::config(SettingsForm::CONFIG_OBJECT);
    $serverId = $this->config->get('ldap_server');
    $this->ldapServer = $entityTypeManager
                      ->getStorage('ldap_server')
                      ->load($serverId);
  }

  /**
   * Determines if an LDAP server has been configured for the service to use for
   * the querying.
   *
   * @return bool
   */
  public function hasLDAPServerConfigured() : bool {
    return isset($this->ldapServer);
  }

  /**
   * Ensures that the LDAP bridge is set to the LDAP server used for directory
   * listing queries and that a connection could be bound.
   */
  public function bind() : void {
    $this->ldapBridge->setServerById($this->ldapServer->get('id'));
    if (!$this->ldapBridge->bind()) {
      throw new Exception('Cannot bind to LDAP server');
    }
  }

  /**
   * Performs an LDAP query to obtain the information for the indicated section.
   *
   * @param string $sectionId
   *
   * @return array
   *  Returns false if the query could not be performed.
   */
  public function querySection(string $sectionId) {
    $section = $this->storage->load($sectionId);
    if (!isset($section)) {
      return false;
    }

    // Get base DN and filter string. The filter string is generated by
    // formatting the section group DN using the configured filter format.
    $baseDN = $this->config->get('base_dn');
    $filterFormat = $this->config->get('filter');
    $filter = sprintf($filterFormat,$section->get('group_dn'));

    if (empty($baseDN) || empty($filter)) {
      return false;
    }

    return $this->doQuery($baseDN,$filter);
  }

  private function doQuery(string $baseDN,string $filter,array $options = []) : array {

    // Prepare attribute filter.
    $attrs = [
      'name_attr',
      'email_attr',
      'title_attr',
      'phone_attr',
    ];

    $options['filter'] = [];
    foreach ($attrs as $name) {
      $attr = $this->config->get($name);
      if (empty($attr)) {
        throw new Exception("Attribute '$name' is not configured");
      }
      $options['filter'][] = $attr;
    }

    $response = $this->ldapBridge
              ->get()
              ->query($baseDN,$filter,$options)
              ->execute()
              ->toArray();

    return $response;
  }
}
